CREATE TABLE MARKET (
    ITIN_ID INT NOT NULL,
    MKT_ID INT NOT NULL AUTO_INCREMENT,
    SEQ_NUM INT NOT NULL,
    YEAR INT NOT NULL,
    QUARTER INT NOT NULL,
    ORIGIN_AIRPORT_ID INT NOT NULL,
    ORIGIN_CITY_MARKET_ID INT NOT NULL,
    ORIGIN_COUNTRY VARCHAR(255) NOT NULL,
    DEST_AIRPORT_ID INT NOT NULL,
    DEST_CITY_MARKET_ID INT NOT NULL,
    DEST_COUNTRY VARCHAR(255) NOT NULL,
    PRIMARY KEY (MKT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
